Smoke test 1.5/2

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -87,6 +87,19 @@ jobs:
           docker run -d -p 5000:5000 --name app-container local-image:${{  github.sha }}
           sleep 10
 
+      - name: Test app reachability
+       run: |
+         # Check if the application is responding
+         HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/)
+         echo "HTTP Status: $HTTP_STATUS"
+         
+         if [[ "$HTTP_STATUS" -ge 200 && "$HTTP_STATUS" -lt 400 ]]; then
+           echo "✅ Application is reachable and returned a success status code: $HTTP_STATUS"
+         else
+           echo "❌ Application is not reachable or returned an error status code: $HTTP_STATUS"
+           exit 1
+         fi
+
       - name: Log in to the Container registry
         uses: docker/login-action@v3
         with:
